# This will set up a node js with yarn, build the application and then build the application, as no actual tests are enabled atm.
# Afterwards it will try to deploy it to Heroku.

name: Node.js CI & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Node install & build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.12.0'
          architecture: 'x64' # optional, x64 or x86. If not specified, x64 will be used by default
      - run: yarn install
      - run: yarn build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "frontend-testing-thesis" #Must be unique in Heroku
          heroku_email: "kyusaki1@gmail.com"
